### ISSUE TITLE
More example

### ISSUE THREAD

**Issue by vanthao03596** [tonysm/turbo-demo-app#5]
@tonysm can u make more example with turbo. Crud with validation on modal would be great

**Comment by tonysm** [comment]
Yeah, modals seem to be a recurring request. Will prepare something.

About CRUDs, what do you mean? Like a regular page with a table where creation and edit are done via modals? Because the app already has validations lists.. just not a "traditional" CRUD UI, I guess.

**Comment by vanthao03596** [comment]
"Like a regular page with a table where creation and edit are done via modals" Yeah like this tony.

**Comment by tonysm** [comment]
I've added a tweets example with modals and flyouts.

https://user-images.githubusercontent.com/1178621/106398624-b253bd80-63f2-11eb-951e-2e43f593bc8d.mp4

**Comment by vanthao03596** [comment]
@tonysm found some issue when using "Edit in Flyout" and "Tweet modal". 
If I click "Edit In Flyout" -> Clear tweet content -> click submit -> we have validation error.
Close flyout and click "Edit" again, validation error still here and we don't have original tweet text.
Same for "Tweet modal".
I think we need call Turbo.visit() when click "Edit in Flyout"

**Comment by tonysm** [comment]
That wouldn't case the frame to refresh. It would simply "visit" the page, no? Which isn't the same. We would need to re-trigger the frame to refresh, which I thought it did.

I have a clue on what could be the issue. Will give something a try here.

**Comment by tonysm** [comment]
@vanthao03596 I've made it refresh the frame inside the flyout every time it opens: https://github.com/tonysm/turbo-demo-app/commit/f7caed4613998dda0c87ef43a4f5e7558133fb59

**Comment by cjaoude** [comment]
If you could, an example with Livewire and file uploads. I'm trying to make a Livewire component that handles fancy file uploads, but once you hit 'upload', Turbo takes over. Don't exactly follow how Turbo & Livewire lifecycles are interacting, some docs on this would be great. tnx. @tonysm

**Comment by cjaoude** [comment]
@tonysm any chance you can do an example of a Livewire form working with Turbo (Frame)? Much needed. Tnx.

**Comment by tonysm** [comment]
@cjaoude can you give me a practical example where you want something like that? I would disable Turbo in a form inside a Livewire component myself (see [here](https://turbo.hotwire.dev/handbook/drive#disabling-turbo-drive-on-specific-links-or-forms)) and let Livewire handle it.

If you want to, you could dispatch Turbo Stream events from Livewire actions and have another Custom Element that handles these events to apply the Turbo Streams. There's an example like that in the demo app ([here's](https://github.com/tonysm/turbo-demo-app/blob/main/app/Http/Livewire/Counter.php#L12-L14) the Livewire component dispatching Turbo Streams and here's the Custom Element [source](https://github.com/tonysm/turbo-demo-app/blob/main/resources/js/elements/turbo-livewire-stream-tag.js) and the [usage](https://github.com/tonysm/turbo-demo-app/blob/main/resources/views/livewire-integration.blade.php#L18)).
